Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CoffeeShopOnline.Models;
using System.IO;

namespace CoffeeShopOnline.Controllers
{
    public class ItemsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Items
        [CustomAuthorizeArtribute(Roles = "Admin,Baristas")]
        public async Task<ActionResult> Index()
        {
            return View(await db.Items.ToListAsync());
        }

        // GET: Items/Details/5
        [CustomAuthorizeArtribute(Roles = "Admin")]
        public async Task<ActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = await db.Items.FindAsync(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // GET: Items/Create
        [CustomAuthorizeArtribute(Roles = "Admin")]
        public ActionResult Create()
        {
            ItemViewModel objItemViewModel = new ItemViewModel();
            objItemViewModel.CategorySelectListItems = (from objCat in db.Categories
                                                        select new SelectListItem()
                                                        {
                                                            Text = objCat.CetegoryName,
                                                            Value = objCat.CategoryId.ToString(),
                                                            Selected = true
                                                        });
            return View(objItemViewModel);
        }

        [CustomAuthorizeArtribute(Roles = "Admin")]
        [HttpPost]
        public  JsonResult Create(ItemViewModel obItemViewModel)
        {
            string NewImage = Guid.NewGuid() + Path.GetExtension(obItemViewModel.ImagePath.FileName);
            obItemViewModel.ImagePath.SaveAs(filename: Server.MapPath("~/Images/" + NewImage));

            Item objItem = new Item();
            objItem.ImagePath = "~/Images/" + NewImage;
            objItem.CatogoryId = obItemViewModel.CategoryId;
            objItem.Decription = obItemViewModel.Description;
            objItem.ItemCode = obItemViewModel.ItemCode;
            objItem.ItemName = obItemViewModel.ItemName;
            objItem.ItemPrice = obItemViewModel.ItemPrice;
            objItem.ItemId = Guid.NewGuid();
            objItem.Quantity = obItemViewModel.Quantity;
            objItem.Promo = obItemViewModel.Promo;
            objItem.PromoPrice = obItemViewModel.PromoPrice;
            objItem.popular =0;
            db.Items.Add(objItem);
            db.SaveChanges();
            return Json(new { Success = true, Message = "Item is added successfully." }, JsonRequestBehavior.AllowGet);
        }

        // GET: Items/Edit/5
        [CustomAuthorizeArtribute(Roles = "Admin")]
        public async Task<ActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = await db.Items.FindAsync(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        [CustomAuthorizeArtribute(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ItemId,CatogoryId,ItemCode,ItemName,Decription,Quantity,ImagePath,ItemPrice,Promo,PromoPrice,PruductOfDay,popular")] Item item)
        {
            if (ModelState.IsValid)
            {
                db.Entry(item).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(item);
        }

        // GET: Items/Delete/5
        [CustomAuthorizeArtribute(Roles = "Admin")]
        public async Task<ActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = await db.Items.FindAsync(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Delete/5
        [CustomAuthorizeArtribute(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(Guid id)
        {
            Item item = await db.Items.FindAsync(id);
            db.Items.Remove(item);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [CustomAuthorizeArtribute(Roles = "Admin")]
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CoffeeShopOnline.Models;

namespace CoffeeShopOnline.Controllers
{
    public class OrdersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Orders
        public async Task<ActionResult> Index()
        {
            return View(await db.Orders.ToListAsync());
        }

        // GET: Orders/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = await db.Orders.FindAsync(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "OrderId,OrderDate,OrderNumber,TableSitTimeEnd,TableNumber,NumberOfDiners,IsAprroved")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Orders.Add(order);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(order);
        }

        // GET: Orders/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = await db.Orders.FindAsync(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "OrderId,OrderDate,OrderNumber,TableSitTimeEnd,TableNumber,NumberOfDiners,IsAprroved")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(order);
        }

        // GET: Orders/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = await db.Orders.FindAsync(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Order order = await db.Orders.FindAsync(id);
            db.Orders.Remove(order);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult BaristaOrder()
        {
            return View();
        }
    }
}

Controllers/PaymentController.cs
using CoffeeShopOnline.Models;
using PayPal.Api;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Item = PayPal.Api.Item;

namespace CoffeeShopOnline.Controllers
{
    public class PaymentController : Controller
    {

        // GET: Payment
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PaymentWithPaypal(string Cancel = null)
        {
            //getting the apiContext
            APIContext apiContext = PaypalConfiguration.GetAPIContext();
            try
            {
                string payerId = Request.Params["PayerID"];
                if (string.IsNullOrEmpty(payerId))
                {
                    string baseURI = Request.Url.Scheme + "://" + Request.Url.Authority + "/Payment/PaymentWithPaypal?";


                    var guid = Convert.ToString((new Random()).Next(100000));
                    var createdPayment = this.CreatePayment(apiContext, baseURI + "guid=" + guid);
                    var links = createdPayment.links.GetEnumerator();
                    string paypalRedirectUrl = null;
                    while (links.MoveNext())
                    {
                        Links lnk = links.Current;
                        if (lnk.rel.ToLower().Trim().Equals("approval_url"))
                        {
                            //saving the payapalredirect URL to which user will be redirected for payment
                            paypalRedirectUrl = lnk.href;
                        }
                    }
                    // saving the paymentID in the key guid
                    Session.Add(guid, createdPayment.id);
                    return Redirect(paypalRedirectUrl);
                }
                else
                {
                    // This function exectues after receving all parameters for the payment
                    var guid = Request.Params["guid"];
                    var executedPayment = ExecutePayment(apiContext, payerId, Session[guid] as string);
                    //If executed payment failed then we will show payment failure message to user
                    if (executedPayment.state.ToLower() != "approved")
                    {
                        return View("FailureView");
                    }

                }

            }

            catch (Exception ex)
            {
                return View("FailureView");
            }
            //on successful payment, show success page to user.
            return View("SuccessView");
        }

        private Payment ExecutePayment(APIContext apiContext, string payerId, string paymentId)
        {
            var paymentExecution = new PaymentExecution()
            {
                payer_id = payerId
            };
            this.payment = new Payment()
            {
                id = paymentId
            };
            return this.payment.Execute(apiContext, paymentExecution);
        }
        private PayPal.Api.Payment payment;

        private Payment CreatePayment(APIContext apiContext, string redirectUrl)
        {
           
            var itemList = new ItemList() { items = new List<Item>() };

            if (Session["CartItem"] != "")
            {
                List<ShoppingCartModel> cart = Session["CartItem"] as List<ShoppingCartModel>;
                foreach (var item in cart)
                {
                    //Adding Item Details like name, currency, price etc
                    itemList.items.Add(new Item()
                    {
                        name = item.ItemName,
                        currency = "USD",
                        price = item.UnitPrice.ToString(),
                        quantity = item.Quantity.ToString(),
                        sku = "sku"
                    });
                }
            }

            var payer = new Payer() { payment_method = "paypal" };

            // Configure Redirect Urls here with RedirectUrls object
            var redirUrls = new RedirectUrls()
            {
                cancel_url = redirectUrl + "&Cancel=true",
                return_url = redirectUrl
            };

            // Adding Tax, shipping and Subtotal details
            var details = new Details()
            {
                tax = "1",
                shipping = "1",
                subtotal = Session["TotalAmount"].ToString(),
                shipping_discount = "-1"
            };

            //Final amount with details
            var amount = new Amount()
            {
                currency = "USD",
                total = (Convert.ToDecimal(Session["TotalAmount"]) + 1).ToString(), // Total must be equal to sum of tax, shipping and subtotal.
                details = details
            };

            var transactionList = new List<Transaction>();
            // Adding description about the transaction
            transactionList.Add(new Transaction()
            {
                description = "Transaction description",
                invoice_number = Convert.ToString((new Random()).Next(100000)),
                amount = amount,
                item_list = itemList
            });


            this.payment = new Payment()
            {
                intent = "sale",
                payer = payer,
                transactions = transactionList,
                redirect_urls = redirUrls
            };

            return this.payment.Create(apiContext);

        }

        [HttpPost]
        public ActionResult SuccessView() {
            return View();
        }
    }
}

Controllers/RoleController.cs
using CoffeeShopOnline.Models;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;


namespace CoffeeShopOnline.Controllers
{
    public class RoleController : Controller
    {
        // GET: Role
        private ApplicationRoleManager _roleManager;
        public RoleController()
        {

        }
        public RoleController(ApplicationRoleManager roleManager)
        {
            RoleManager = roleManager;

        }
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }

        }
        [CustomAuthorizeArtribute(Roles = "Admin")]
        public ActionResult Index()
        {
            List<RoleViewModel> list = new List<RoleViewModel>();
            foreach (var role in RoleManager.Roles)
                list.Add(new RoleViewModel(role));
            return View(list);
        }

        [CustomAuthorizeArtribute(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        [CustomAuthorizeArtribute(Roles = "Admin")]
        [HttpPost]
        public async Task<ActionResult> Create(RoleViewModel model)
        {
            var role = new ApplicationRole() { Name = model.Name };
            await RoleManager.CreateAsync(role);
            return RedirectToAction("Index");
        }

        [CustomAuthorizeArtribute(Roles = "Admin")]
        public async Task<ActionResult> Edit(string id)
        {
            var role = await RoleManager.FindByIdAsync(id);
            return View(new RoleViewModel(role));
        }

        [CustomAuthorizeArtribute(Roles = "Admin")]
        [HttpPost]
        public async Task<ActionResult> Edit(RoleViewModel model)
        {
            var role = new ApplicationRole() { Id = model.Id, Name = model.Name };
            await RoleManager.UpdateAsync(role);
            return RedirectToAction("Index");
        }

        [CustomAuthorizeArtribute(Roles = "Admin")]
        public async Task<ActionResult> Details(string id)
        {
            var role = await RoleManager.FindByIdAsync(id);
            return View(new RoleViewModel(role));
        }

        [CustomAuthorizeArtribute(Roles = "Admin")]
        public async Task<ActionResult> Delete(string id)
        {
            var role = await RoleManager.FindByIdAsync(id);
            return View(new RoleViewModel(role));
        }

        [CustomAuthorizeArtribute(Roles = "Admin")]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            var role = await RoleManager.FindByIdAsync(id);
            await RoleManager.DeleteAsync(role);
            return RedirectToAction("Index");
        }

    }
}

Views/Shared/AuthorizeFailed.cshtml
@{
    ViewBag.Title = "Authorize Failed";
}

<h2>AuthorizeFailed</h2>

<p>@ViewData["Message"]</p>

Views/Shared/ShoppingCart.cshtml
@model IEnumerable<CoffeeShopOnline.Models.ShoppingCartModel>

@{
    ViewBag.Title = "ShoppingCart";
    decimal TotalAmount = 0.00M;
    var message = TempData["Message"] ?? string.Empty;

}
<script type="text/javascript">
var message = '@message';
if(message)
        alert(message);

    Session["TotalAmount"] = TotalAmount;

</script>
<h2>ShoppingCart</h2>

@using (Html.BeginForm("Index", "Payment"))
{


<table class="table-condensed " style="width:100%">
    @if (Model != null)
    {
        foreach (var item in Model)
        {
            item.popular += 1;
            TotalAmount += item.Total;
            <tr>
                <td>
                    <img src="@Url.Content(item.ImagePath)" height="50" width="50" class="img-rounded" />
                </td>
                <td>
                    @item.ItemName
                </td>
                <td style="text-align:right">
                    @item.Quantity.ToString("#,##0.00")
                </td>
                <td style="text-align:right">

                    @item.UnitPrice.ToString("#,##0.00 $")
                </td>
                <td style="text-align:right">
                    @item.Total.ToString("#,##0.00 $")
                </td>

                <td>
                    <a href="@Url.Action("RemoveFromCart", "Shopping", new { itemId = item.ItemId })">Remove</a>
                </td>
            </tr>
        }
        <tr style="border-top: 2px solid maroon">
            <td colspan="4" style="text-align:right">
                <h3>Total Amount</h3>
            </td>
            <td style="text-align:right">
                <h3>@TotalAmount.ToString("#,##0.00 $")</h3>

            </td>

        </tr>

        <tr style="text-align:right">
            <td colspan="5">
                <input type="submit" value="Save" name="Save" class="btn btn=primary" id="SaveOrder" />
            </td>
        </tr>

        <tr style="text-align:left">
            <td colspan="5">
                @Html.ActionLink("Back to To Buy More", "Index")
            </td>
        </tr>

    }
    else
    {

        <h3>The Cart is Empty</h3>
        if (Session["table"] != null)
        {

        <tr style="text-align:center">
            <td colspan="5">
                @Html.ActionLink("Buy Something", "Index")

            </td>
        </tr>
        }
        else
        {
            @Html.ActionLink("Choose a table", "OnlineOrder", "Home");
        }

    }

</table>
}

Views/Shared/_CartPartial.cshtml
<ul class="nav navbar-nav navbar-brand">
    <li>
        @if (Session["CartCounter"] == null)
        {
            @Html.ActionLink("Cart", "ShoppingCart", "Shopping", routeValues: null, new { id = "cartItem" })

        }
        else
        {
            @Html.ActionLink("Cart(" + Session["CartCounter"] + ")", "ShoppingCart", "Shopping", routeValues: null, new { id = "cartItem" })
        }
    </li>

</ul>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GTR Coffee-Shop</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <link href="~/assets/Layout/img/coffeeF.jpg" rel="icon">
    <link href="~/assets/Layout/img/coffeeF.jpg" rel="apple-touch-icon">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,300i,400,400i,600,600i,700,700i|Satisfy|Comic+Neue:300,300i,400,400i,700,700i" rel="stylesheet">

    <link href="~/assets/Layout/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="~/assets/Layout/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/Layout/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/Layout/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/Layout/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/assets/Layout/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <link href="~/assets/Layout/css/style.css" rel="stylesheet" />
</head>
<body>

    <section id="topbar" class="d-flex align-items-center fixed-top ">
        <div class="container-fluid container-xl d-flex align-items-center justify-content-center justify-content-lg-start">
            <i class="bi bi-phone d-flex align-items-center"><span>+972 08-610-5555</span></i>
            <i class="bi bi-clock ms-4 d-none d-lg-flex align-items-center"><span>Sun-Sat: 7:00 AM - 23:00 PM</span></i>
        </div>
    </section>
   <header id="header" class="fixed-top d-flex align-items-center ">
       <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

           <div class="logo me-auto">
               <h1><a href="/Home/OnlineOrder">GTR&Coffee</a></h1>
               <!-- Uncomment below if you prefer to use an image logo -->
               <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
           </div>

           <nav id="navbar" class="navbar order-last order-lg-0">


               @Html.ActionLink("דף הבית", "OnlineOrder", "Home")
               @Html.ActionLink("כתובת", "Contact", "Home")
               @Html.ActionLink("עלינו", "About", "Home")

               @if (User.IsInRole("Admin"))
               {
                   <ul>
                       <li class="dropdown">
                           <a href="#"><span>מנהל</span> <i class="bi bi-chevron-down"></i></a>
                           <ul>
                               <li>
                                   @Html.ActionLink("הוסף קטגוריה", "Index", "Categories")
                               </li>
                               <li>
                                   @Html.ActionLink("הוסף מוצר", "Index", "Items")
                               </li>

                               <li>
                                   @Html.ActionLink("שולחונות", "Index", "RoomTables")
                               </li>
                               <li>
                                   @Html.ActionLink("תפקידים", "Index", "Role")
                               </li>
                           </ul>
                       </li>
                   </ul>
               }
               @if (User.IsInRole("Baristas") || User.IsInRole("Admin"))
               {

                   @Html.ActionLink("כל ההזמנות", "Index", "Orders")
                   @Html.ActionLink("בצע הזמנה חדשה", "BaristaOrder", "Barista")

               }
               <li>
               </li>
               <i class="bi bi-list mobile-nav-toggle"></i>
           </nav><!-- .navbar -->
          @Html.Partial("_CartPartial")

           

       </div>
    </header><!-- End Header -->

    <main id="main">

        <!-- ======= Breadcrumbs Section ======= -->
        <section class="breadcrumbs" id="log">
            <div class="container">

                <div class="d-flex justify-content-between align-items-center" >
                    <h2></h2>
                    <ol>
                        @Html.Partial("_LoginPartial")
                    </ol>
                </div>

            </div>
        </section><!-- End Breadcrumbs Section -->

        <section class="inner-page">
            <div class="container">
                <p>
                    @RenderBody()
                </p>
            </div>
        </section>

    </main>
    <hr />
    <footer id="footer">
        <div class="container">
            <h3>GTR&Coffee</h3>
            <p>The bast coffee at the world,just try it and be Happy!</p>
            
            
        </div>
    </footer>

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <script src="~/assets/Layout/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/Layout/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/assets/Layout/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/Layout/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/assets/Layout/vendor/php-email-form/validate.js"></script>

    <script src="~/assets/Layout/js/main.js"></script>

</body>

</html>

<style>
      body {
        background-color: rgb(70 150 68 / 0.50);
        background-size: cover;
        background-repeat: no-repeat;
        height: 100%;
        font-family: 'Numans', sans-serif;
    }
    #log {
        background-color: rgb(85 130 85 / 0.25);
        background-size: cover;
    }
</style>