Controllers/PaymentController.cs
using CoffeeShopOnline.Models;
using PayPal.Api;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Item = PayPal.Api.Item;

namespace CoffeeShopOnline.Controllers
{
    public class PaymentController : Controller
    {

        // GET: Payment
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PaymentWithPaypal(string Cancel = null)
        {
            //getting the apiContext
            APIContext apiContext = PaypalConfiguration.GetAPIContext();
            try
            {
                string payerId = Request.Params["PayerID"];
                if (string.IsNullOrEmpty(payerId))
                {
                    string baseURI = Request.Url.Scheme + "://" + Request.Url.Authority + "/Payment/PaymentWithPaypal?";


                    var guid = Convert.ToString((new Random()).Next(100000));
                    var createdPayment = this.CreatePayment(apiContext, baseURI + "guid=" + guid);
                    var links = createdPayment.links.GetEnumerator();
                    string paypalRedirectUrl = null;
                    while (links.MoveNext())
                    {
                        Links lnk = links.Current;
                        if (lnk.rel.ToLower().Trim().Equals("approval_url"))
                        {
                            //saving the payapalredirect URL to which user will be redirected for payment
                            paypalRedirectUrl = lnk.href;
                        }
                    }
                    // saving the paymentID in the key guid
                    Session.Add(guid, createdPayment.id);
                    return Redirect(paypalRedirectUrl);
                }
                else
                {
                    // This function exectues after receving all parameters for the payment
                    var guid = Request.Params["guid"];
                    var executedPayment = ExecutePayment(apiContext, payerId, Session[guid] as string);
                    //If executed payment failed then we will show payment failure message to user
                    if (executedPayment.state.ToLower() != "approved")
                    {
                        return View("FailureView");
                    }

                }

            }

            catch (Exception ex)
            {
                return View("FailureView");
            }
            //on successful payment, show success page to user.
            return View("SuccessView");
        }

        private Payment ExecutePayment(APIContext apiContext, string payerId, string paymentId)
        {
            var paymentExecution = new PaymentExecution()
            {
                payer_id = payerId
            };
            this.payment = new Payment()
            {
                id = paymentId
            };
            return this.payment.Execute(apiContext, paymentExecution);
        }
        private PayPal.Api.Payment payment;

        private Payment CreatePayment(APIContext apiContext, string redirectUrl)
        {
           
            var itemList = new ItemList() { items = new List<Item>() };

            if (Session["CartItem"] != "")
            {
                List<ShoppingCartModel> cart = Session["CartItem"] as List<ShoppingCartModel>;
                foreach (var item in cart)
                {
                    //Adding Item Details like name, currency, price etc
                    itemList.items.Add(new Item()
                    {
                        name = item.ItemName,
                        currency = "USD",
                        price = item.UnitPrice.ToString(),
                        quantity = item.Quantity.ToString(),
                        sku = "sku"
                    });
                }
            }

            var payer = new Payer() { payment_method = "paypal" };

            // Configure Redirect Urls here with RedirectUrls object
            var redirUrls = new RedirectUrls()
            {
                cancel_url = redirectUrl + "&Cancel=true",
                return_url = redirectUrl
            };

            // Adding Tax, shipping and Subtotal details
            var details = new Details()
            {
                tax = "1",
                shipping = "1",
                subtotal = Session["TotalAmount"].ToString(),
                shipping_discount = "-1"
            };

            //Final amount with details
            var amount = new Amount()
            {
                currency = "USD",
                total = (Convert.ToDecimal(Session["TotalAmount"]) + 1).ToString(), // Total must be equal to sum of tax, shipping and subtotal.
                details = details
            };

            var transactionList = new List<Transaction>();
            // Adding description about the transaction
            transactionList.Add(new Transaction()
            {
                description = "Transaction description",
                invoice_number = Convert.ToString((new Random()).Next(100000)),
                amount = amount,
                item_list = itemList
            });


            this.payment = new Payment()
            {
                intent = "sale",
                payer = payer,
                transactions = transactionList,
                redirect_urls = redirUrls
            };

            return this.payment.Create(apiContext);

        }

        [HttpPost]
        public ActionResult SuccessView() {
            return View();
        }
    }
}

Controllers/ShoppingController.cs
using CoffeeShopOnline.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CoffeeShopOnline.Controllers
{
    public class ShoppingController : Controller
    {

        private ApplicationDbContext db;
        private List<ShoppingCartModel> listOfShoppingCartModel;
        private decimal TotalAmount = 0.00M;

        public ShoppingController()
        {
            db = new ApplicationDbContext();
            listOfShoppingCartModel = new List<ShoppingCartModel>();
        }
        // GET: Shopping
        public ActionResult Index()
        {

            var closeParty = Convert.ToBoolean(Session["Party"]);
            var talbenumber = Convert.ToDecimal(Session["table"]);
            RoomTable roomTable = db.RoomTables.Single(model => model.Id == talbenumber);
            IEnumerable<ShoppingViewModel> listOfShoppingViewModels = (from objItem in db.Items
                                                                       join
                                                                       objCate in db.Categories
                                                                       on objItem.CatogoryId equals objCate.CategoryId
                                                                       select new ShoppingViewModel()
                                                                       {
                                                                           ImagePath = objItem.ImagePath,
                                                                           ItemName = objItem.ItemName,
                                                                           ItemId = objItem.ItemId,
                                                                           ItemPrice = objItem.ItemPrice,
                                                                           Description = objItem.Decription,
                                                                           ItemCode = objItem.ItemCode,
                                                                           Category = objCate.CetegoryName,
                                                                           Popular=objItem.popular,
                                                                           Quantity=objItem.Quantity,
                                                                           Promo=objItem.Promo,
                                                                           PromoPrice=objItem.PromoPrice,
                                                                           PruductOfDay=objItem.PruductOfDay, 
                                                                           InOrOutTable=roomTable.InOrOut,
                                                                           ClosedParty = closeParty,
                                                                           DishOfDay=false
                                                                       }
                                                                      ).ToList();

            
                return View(listOfShoppingViewModels);
        }

        [HttpPost]
        public JsonResult Index(string ItemId)
        {
            if(Session["TotalAmount"]!=null)
                TotalAmount = (decimal)Session["TotalAmount"];
            ShoppingCartModel ob = new ShoppingCartModel();
            Item objItem = db.Items.Single(model => model.ItemId.ToString() == ItemId);
            if (Session["CartCounter"] != null)
            {
                listOfShoppingCartModel = Session["CartItem"] as List<ShoppingCartModel>;
            }
            if (listOfShoppingCartModel.Any(model => model.ItemId == ItemId))
            {

                ob = listOfShoppingCartModel.Single(model => model.ItemId == ItemId);
                if (ob.TotalQuantity > 0)
                {
                    ob.Quantity = ob.Quantity + 1;
                    ob.Total = ob.Quantity * ob.UnitPrice;
                    ob.TotalQuantity = (int)(objItem.Quantity - ob.Quantity);
                    TotalAmount+= ob.Total;
                }
                else
                {

                    return Json(new { Success = false, Message = "No more " + objItem.ItemName + " item to add to cart,out of stack!", Counter = listOfShoppingCartModel.Count }, JsonRequestBehavior.AllowGet);

                }

            }
            else
            {
                if (objItem.CatogoryId == 3)
                {
                    var nv = User.Identity.Name;
                    if (User.Identity.IsAuthenticated)
                    {
                        var update = (from c in db.Users
                                      where c.UserName == nv
                                      select c).SingleOrDefault();
                        if (update.Age >= 18)
                        {
                            ob.ItemId = ItemId;
                            ob.ImagePath = objItem.ImagePath;
                            ob.ItemName = objItem.ItemName;
                            ob.Quantity = 1;
                            ob.Total = (decimal)objItem.ItemPrice;
                            ob.UnitPrice = (decimal)objItem.ItemPrice;
                            ob.Category = objItem.CatogoryId;
                            ob.TotalQuantity = objItem.Quantity - 1;
                            TotalAmount += ob.UnitPrice;
                            listOfShoppingCartModel.Add(ob);
                        }
                        else
                        {
                            return Json(new { Success = false, Message = "cant buy אלכוהול when you not 18+", Counter = listOfShoppingCartModel.Count }, JsonRequestBehavior.AllowGet);
                        }
                    }

                    else
                    {
                        return Json(new { Success = false, Message = "cant buy אלכוהול when you not login", Counter = listOfShoppingCartModel.Count }, JsonRequestBehavior.AllowGet);
                    }
                }
                else
                {
                    ob.ItemId = ItemId;
                    ob.ImagePath = objItem.ImagePath;
                    ob.ItemName = objItem.ItemName;
                    ob.Quantity = 1;
                    if(objItem.Promo && (@DateTime.Now.Hour < 17 && DateTime.Now.Hour > 12))
                    {
                        ob.UnitPrice = objItem.PromoPrice;
                        ob.Total = objItem.PromoPrice;
                        TotalAmount += ob.UnitPrice;
                    }
                    else
                    {
                        ob.Total = (decimal)objItem.ItemPrice;
                        ob.UnitPrice = (decimal)objItem.ItemPrice;
                        TotalAmount += ob.UnitPrice;

                    }
                    ob.Category = objItem.CatogoryId;
                    ob.TotalQuantity = objItem.Quantity - 1;

                    listOfShoppingCartModel.Add(ob);
                }
            }

            Session["TotalAmount"] = TotalAmount;
            Session["CartCounter"] = listOfShoppingCartModel.Count;
            Session["CartItem"] = listOfShoppingCartModel;

            return Json(new { Success = true, Counter = listOfShoppingCartModel.Count }, JsonRequestBehavior.AllowGet);

        }

        public ActionResult business_lunch()
        {
            IEnumerable<ShoppingViewModel> listOfShoppingViewModels = (from objItem in db.Items
                                                                       join
                                                                       objCate in db.Categories
                                                                       on objItem.CatogoryId equals objCate.CategoryId
                                                                       select new ShoppingViewModel()
                                                                       {
                                                                           ImagePath = objItem.ImagePath,
                                                                           ItemName = objItem.ItemName,
                                                                           ItemId = objItem.ItemId,
                                                                           ItemPrice = objItem.ItemPrice,
                                                                           Description = objItem.Decription,
                                                                           ItemCode = objItem.ItemCode,
                                                                           Category = objCate.CetegoryName,
                                                                           Popular = objItem.popular,
                                                                           Quantity = objItem.Quantity,
                                                                           Promo = objItem.Promo,
                                                                           PromoPrice = objItem.PromoPrice

                                                                       }
                                                                                  ).ToList();

           
            return View(listOfShoppingViewModels);
        }

        public ActionResult ShoppingCart()
        {
            listOfShoppingCartModel = Session["CartItem"] as List<ShoppingCartModel>;
            var Username = Session["Username"];
            if (Username != null)
            {
                if (db.Users.Any(model => model.UserName == Username.ToString()))
                {
                    var update = (from c in db.Users

Views/Payment/FailureView.cshtml
@{

    ViewBag.Title = "PaymentWithPaypal";
}


<h2>PaymentWithPaypal</h2>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>FailureView</title>
</head>
<body>
    <div>
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
        <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="error-template">
                        <h1>
                            Oops!
                        </h1>

                        <div class="error-details">
                            Sorry, Payment has not successfully done!
                        </div>
                        <div class="error-actions">
                                <span class="glyphicon glyphicon-home"></span>
                                Take Me Home
                            </a><a href="@Url.Action("Index","Home")" class="btn btn-default btn-lg"><span class="glyphicon glyphicon-envelope"></span> Go Home </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</body>
</html>


<style>
    body {
        background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABoAAAAaCAYAAACpSkzOAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAABZ0RVh0Q3JlYXRpb24gVGltZQAxMC8yOS8xMiKqq3kAAAAcdEVYdFNvZnR3YXJlAEFkb2JlIEZpcmV3b3JrcyBDUzVxteM2AAABHklEQVRIib2Vyw6EIAxFW5idr///Qx9sfG3pLEyJ3tAwi5EmBqRo7vHawiEEERHS6x7MTMxMVv6+z3tPMUYSkfTM/R0fEaG2bbMv+Gc4nZzn+dN4HAcREa3r+hi3bcuu68jLskhVIlW073tWaYlQ9+F9IpqmSfq+fwskhdO/AwmUTJXrOuaRQNeRkOd5lq7rXmS5InmERKoER/QMvUAPlZDHcZRhGN4CSeGY+aHMqgcks5RrHv/eeh455x5KrMq2yHQdibDO6ncG/KZWL7M8xDyS1/MIO0NJqdULLS81X6/X6aR0nqBSJcPeZnlZrzN477NKURn2Nus8sjzmEII0TfMiyxUuxphVWjpJkbx0btUnshRihVv70Bv8ItXq6Asoi/ZiCbU6YgAAAABJRU5ErkJggg==);
    }

    .error-template {
        padding: 40px 15px;
        text-align: center;
    }

    .error-actions {
        margin-top: 15px;
        margin-bottom: 15px;
    }

        .error-actions .btn {
            margin-right: 10px;
        }
</style>

Views/Payment/Index.cshtml
<script src="~/Scripts/jquery-3.6.0.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>


<div class="container py-5">
    <!-- For demo purpose -->
    <div class="row mb-4">
        <div class="col-lg-8 mx-auto text-center">
            <h1 class="display-6"> Payment </h1>
        </div>
    </div> <!-- End -->
    <div class="row">
        <div class="col-lg-6 mx-auto">
            <div class="card ">
                <div class="card-header">
                    <div class="bg-white shadow-sm pt-4 pl-2 pr-2 pb-2">
                        <!-- Credit card form tabs -->
                        <ul role="tablist" class="nav bg-light nav-pills rounded nav-fill mb-3">
                            <li class="nav-item"> <a data-toggle="pill" href="#credit-card" class="nav-link active "> <i class="fas fa-credit-card mr-2"></i> Credit Card </a> </li>
                            <li class="nav-item"> <a data-toggle="pill" href="#paypal" class="nav-link "> <i class="fab fa-paypal mr-2"></i> Paypal </a> </li>
                            <li class="nav-item"> <a data-toggle="pill" href="#net-banking" class="nav-link "> <i class="bi bi-cash"></i> Cash </a> </li>
                        </ul>
                    </div> <!-- End -->
                    <!-- Credit card form content -->
                    @using (Html.BeginForm("SuccessView", "Payment", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                    {
                        <div class="tab-content">
                            <!-- credit card info-->
                            <div id="credit-card" class="tab-pane fade show active pt-3">
                                <form role="form" onsubmit="event.preventDefault()">
                                    <div class="form-group">
                                        <label for="username">
                                            <h6>Card Owner</h6>
                                        </label> <input type="text" name="username" placeholder="Card Owner Name" required class="form-control ">
                                    </div>
                                    <div class="form-group">
                                        <label for="cardNumber">
                                            <h6>Card number</h6>
                                        </label>
                                        <div class="input-group">
                                            <input type="text" name="cardNumber" placeholder="Valid card number" class="form-control " required>
                                            <div class="input-group-append"> <span class="input-group-text text-muted"> <i class="fab fa-cc-visa mx-1"></i> <i class="fab fa-cc-mastercard mx-1"></i> <i class="fab fa-cc-amex mx-1"></i> </span> </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-8">
                                            <div class="form-group">
                                                <label>
                                                    <span class="hidden-xs">
                                                        <h6>Expiration Date</h6>
                                                    </span>
                                                </label>
                                                <div class="input-group"> <input type="number" placeholder="MM" name="" class="form-control" required> <input type="number" placeholder="YY" name="" class="form-control" required> </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-4">
                                            <div class="form-group mb-4">
                                                <label data-toggle="tooltip" title="Three digit CV code on the back of your card">
                                                    <h6>CVV <i class="fa fa-question-circle d-inline"></i></h6>
                                                </label> <input type="text" required class="form-control">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card-footer"> <button type="submit" class="subscribe btn btn-primary btn-block shadow-sm"> Confirm Payment </button>
                                </form>
                            </div>
                        </div> <!-- End -->
                    }
                    <!-- Paypal info -->
                    <div id="paypal" class="tab-pane fade pt-3">
                        <h6 class="pb-2">Select your paypal account type</h6>
                    </div> <!-- End -->
                    <!-- bank transfer info -->
                    <div id="net-banking" class="tab-pane fade pt-3">
                        <div class="form-group ">
                            <label for="cash">
                                <h6>Cash</h6>
                            </label>

                        </div>
                        @using (Html.BeginForm("SuccessView", "Payment", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                        {
                            <div class="form-group">
                                <p> <button type="submit" class="btn btn-primary "><i class="fas fa-mobile-alt mr-2"></i> Proceed Payment</button> </p>
                            </div>
                        }
                    </div> <!-- End -->
                    <!-- End -->
                </div>
            </div>
        </div>
    </div>
</div>
@using (Html.BeginForm("PaymentWithPaypal", "Payment", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <p> <button type="submit" class="btn btn-primary "><i class="fab fa-paypal mr-2"></i> Log into my Paypal</button> </p>
}

<style>
    body {
        background: #f5f5f5
    }

    .rounded {
        border-radius: 1rem
    }

    .nav-pills .nav-link {
        color: #555
    }

        .nav-pills .nav-link.active {
            color: white
        }

    input[type="radio"] {
        margin-right: 5px
    }

    .bold {
        font-weight: bold
    }
</style>

<script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
</script>

Views/Payment/PaymentWithPaypal.cshtml
@{
    ViewBag.Title = "PaymentWithPaypal";
}


<h2>PaymentWithPaypal</h2>

Views/Payment/SuccessView.cshtml
@{
    ViewBag.Title = "PaymentWithPaypal";
}




<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Success</title>
</head>
<body>
    <div>
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
        <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="error-template">
                        <h1>
                            Good
                        </h1>

                        <div class="error-details">
                            Payment has successfully done!
                        </div>
                        <div class="error-actions">
                            @if (User.IsInRole("Baristas"))
                            {
                                using (Html.BeginForm("AddOrderBarista", "Barista", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                                {
                                    <input type="submit" class="btn btn-default btn-lg" value="Take Me Home" /><span class="glyphicon glyphicon-home"></span>
                                }

                            }
                            else
                            {
                                using (Html.BeginForm("AddOrder", "Shopping", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                                {
                                    <input type="submit" class="btn btn-default btn-lg" value="Take Me Home" /><span class="glyphicon glyphicon-home"></span>

                                }
                            }
                           
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>


<style>
    body {
        background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABoAAAAaCAYAAACpSkzOAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAABZ0RVh0Q3JlYXRpb24gVGltZQAxMC8yOS8xMiKqq3kAAAAcdEVYdFNvZnR3YXJlAEFkb2JlIEZpcmV3b3JrcyBDUzVxteM2AAABHklEQVRIib2Vyw6EIAxFW5idr///Qx9sfG3pLEyJ3tAwi5EmBqRo7vHawiEEERHS6x7MTMxMVv6+z3tPMUYSkfTM/R0fEaG2bbMv+Gc4nZzn+dN4HAcREa3r+hi3bcuu68jLskhVIlW073tWaYlQ9+F9IpqmSfq+fwskhdO/AwmUTJXrOuaRQNeRkOd5lq7rXmS5InmERKoER/QMvUAPlZDHcZRhGN4CSeGY+aHMqgcks5RrHv/eeh455x5KrMq2yHQdibDO6ncG/KZWL7M8xDyS1/MIO0NJqdULLS81X6/X6aR0nqBSJcPeZnlZrzN477NKURn2Nus8sjzmEII0TfMiyxUuxphVWjpJkbx0btUnshRihVv70Bv8ItXq6Asoi/ZiCbU6YgAAAABJRU5ErkJggg==);
    }

    .error-template {
        padding: 40px 15px;
        text-align: center;
    }

    .error-actions {
        margin-top: 15px;
        margin-bottom: 15px;
    }

        .error-actions .btn {
            margin-right: 10px;
        }
</style>